version: '3.9'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db 

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: S4vagery
      POSTGRES_DB: admin

    volumes:
      - .db-data:/var/lib/postgresql/data
    ports:
      - "5455:5432"